---
- name: Manage software packages and services
  hosts: all
  become: yes

  tasks:
    - name: Install Apache web server
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Ensure Apache service is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy custom index.html page
      ansible.builtin.copy:
        content: "<h1>Hello from Ansible - Managed Node</h1>"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
