---
- name: Advanced user and group management
  hosts: all
  become: yes   
  vars:
    users_list:
      - name: alice
        groups: developers
        password: "{{ 'root123' | password_hash('sha512') }}"
        sudo: yes
      - name: bob
        groups: testers
        password: "{{ 'pass123' | password_hash('sha512') }}"
        sudo: no

  tasks:

    - name: Ensure /etc/sudoers.d directory exists
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'

    - name: Ensure groups exist
      ansible.builtin.group:
        name: "{{ item.groups }}"
        state: present
      loop: "{{ users_list }}"

    - name: Create users with password and home directories
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password }}"
        state: present
        create_home: yes
      loop: "{{ users_list }}"

    - name: Add sudo privileges to selected users
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ item.name }}"
        content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
      loop: "{{ users_list }}"
      when: item.sudo | bool

